### ISSUE TITLE
Error in FileDownload step at very beginning of a hgtag (release) build

### ISSUE THREAD

**Issue by gracinet** [anybox/anybox.buildbot.odoo#4]
During some release builds, I got this on several buildslaves:

```
Traceback from remote host -- Traceback (most recent call last):
(...)_
  File "/srv/buildslave/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/srv/buildslave/local/lib/python2.7/site-packages/buildslave/commands/transfer.py", line 285, in start
    os.makedirs(dirname)
  File "/srv/buildslave/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
exceptions.OSError: [Errno 17] File exists: '/srv/buildslave/slavedir/myproject-release-postgresql-9_3/build/../src'
exceptions.OSError: [Errno 17] File exists: '/srv/buildslave/slavedir/myproject-release-postgresql-9_3/build/../src'
```

Explanation: the `build/` subdir does not exist, therefore `os.path.exists('build/../src')` returns False, and that trigger the `makedirs` on a directory that actually exists (something at lower level probably normalizes a bit more before creating)

Since this `FileDownload` has been there since the inception of the 'hgtag' token, I suppose this error can happen only after previous errors at some precise point.

Anyway, `workdir=src` will be cleaner than `../src`

**Comment by gracinet** [comment]
Fixed long ago, working since then
